name: Build Linux x64

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-linux64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install upstream dmd
      run: curl -fsS https://dlang.org/install.sh | bash -s dmd

    - name: Set upstream dmd to PATH
      run: |
        source ~/dlang/dmd-2.108.0/activate
        make dmd
        make druntime
    
    - name: Make dmd executable
      run: chmod +x ./generated/linux/release/64/dmd

    - name: Create tarball
      run: tar -czf opend_linux_x64.tar.gz -C generated/linux/release/64 .

    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
          name: opend_linux_x64.tar.gz
          path: opend_linux_x64.tar.gz
    
    - name: Pulbish artifact
      uses: actions/upload-artifact@v4
      with:
        name: opend_linux_x64
        path: opend_linux_x64    
      
  build-win64:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
            
    - name: Build dmd build tool
      run: ${{ github.workspace }}\ci\build_deps\dmd.2.108.8\windows\bin64\dmd.exe build
      shell: powershell
      working-directory: compiler\src

    - name: Build odmd compiler
      run: .\build.exe
      shell: powershell
      working-directory: compiler\src
      env: 
        HOST_DMD: ${{ github.workspace }}\ci\build_deps\dmd.2.108.8\windows\bin64\dmd.exe

    - name: Enable developer command prompt # required to build druntime
      uses: ilammy/msvc-dev-cmd@v1.13.0

    - name: Build druntime
      run: ${{ github.workspace }}\ci\build_deps\winmake-3.81\bin\make.exe
      shell: cmd
      working-directory: druntime

    - name: Build phobos
      run: ${{ github.workspace }}\ci\build_deps\winmake-3.81\bin\make.exe
      shell: cmd
      working-directory: phobos

    - name: Create tarball
      run: tar -czf --verbose opend_windows_x64.tar.gz -C ${{ github.workspace }}\generated\windows\release\64 . -C ${{ github.workspace }}\phobos\generated\windows\release\64 .


  make-release:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: opend_linux_x64

      - name: Pulbish artifact
        uses: actions/upload-artifact@v4
        with:
          name: opend_linux_x64
          path: opend_linux_x64
