name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install upstream dmd
      run: curl -fsS https://dlang.org/install.sh | bash -s dmd

    - name: Make dmd
      run: make dmd

    - name: Make druntime
      run: make druntime
