name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install upstream dmd
      run: curl -fsS https://dlang.org/install.sh | bash -s dmd

    - name: Set upstream dmd to PATH
      run: source ~/dlang/dmd-2.108.0/activate

    - name: Make dmd
      env: 
        HOST_DMD: ~/dlang/dmd-2.108.0/linux/bin64/dmd
      run: make dmd

    - name: Make druntime
      run: make druntime
