name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install upstream dmd
      run: curl -fsS https://dlang.org/install.sh | bash -s dmd

    - name: Set upstream dmd to PATH
      run: |
        source ~/dlang/dmd-2.108.0/activate
        make dmd
        make druntime

    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
          name: linux-x86_64
          path: |
            generated/linux/release/64
