name: Build Widows x64

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    # - name: Install upstream dmd
    #   run: curl -fsS https://dlang.org/install.sh | bash -s dmd

    - name: Test
      run: ls
      shell: powershell

    - name: Build dmd build tool
      run: ${{ github.workspace }}\ci\build_deps\dmd.2.108.8\windows\bin64\dmd.exe build
      shell: powershell
      working-directory: compiler\src

    - name: Build odmd compiler
      run: .\build.exe
      shell: powershell
      working-directory: compiler\src
      env: 
        HOST_DMD: ${{ github.workspace }}\ci\build_deps\dmd.2.108.8\windows\bin64\dmd.exe

    - name: Build druntime
      run: ${{ github.workspace }}\ci\build_deps\winmake-3.81\bin\make.exe
      shell: powershell
      working-directory: druntime
    
    # - name: Make dmd executable
    #   run: chmod +x ./generated/linux/release/64/dmd

    # - name: Create tarball
    #   run: tar -czf opend_linux_x64.tar.gz -C generated/linux/release/64 .

    # - name: Archive production artifacts
    #   uses: actions/upload-artifact@v4
    #   with:
    #       name: opend_windows_x64.tar.gz
    #       path: opend_windows_x64.tar.gz
            
    # - name: Create Release
    #   uses: ncipollo/release-action@v1.14.0
    #   with:
    #     tag: Nightly
    #     artifacts: opend_windows_x64.tar.gz
            
      
