name: Build Widows x64

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
            
    - name: Build dmd build tool
      run: ${{ github.workspace }}\ci\build_deps\dmd.2.108.8\windows\bin64\dmd.exe build
      shell: powershell
      working-directory: compiler\src

    - name: Build odmd compiler
      run: .\build.exe
      shell: powershell
      working-directory: compiler\src
      env: 
        HOST_DMD: ${{ github.workspace }}\ci\build_deps\dmd.2.108.8\windows\bin64\dmd.exe

    - name: Enable developer command prompt # required to build druntime
      uses: ilammy/msvc-dev-cmd@v1.13.0

    - name: Build druntime
      run: ${{ github.workspace }}\ci\build_deps\winmake-3.81\bin\make.exe
      shell: cmd
      working-directory: druntime

    - name: Build phobos
      run: ${{ github.workspace }}\ci\build_deps\winmake-3.81\bin\make.exe
      shell: cmd
      working-directory: phobos

    - name: test
      run: |
        ls phobos/generated/
        ls druntime

    - name: Create tarball
      run: tar -czf opend_windows_x64.tar.gz -C generated\windows\release\64 . -C phobos\generated .

    - name: Pulbish artifact
      uses: actions/upload-artifact@v4
      with:
          name: opend_windows_x64
          path: generated\windows\release\64
            
    # - name: Create Release
    #   uses: ncipollo/release-action@v1.14.0
    #   with:
    #     tag: Nightly
    #     artifacts: opend_windows_x64.tar.gz
            
      
